<?php
  $restaurants_itau = array(
   array(
   "name" => "Yoko's Sushi Express",
   "sub" => "&nbsp;",
   "slug" => "yoko-s-sushi-express",
   "address" => " Av. Camaño 1103 (Vía Pilar). Pilar",
   "food-type" => "China",
   "price" => "$$",
   "discount" => "20",
   ),
   array(
   "name" => "Yoko's",
   "sub" => "(Maschwitz)",
   "slug" => "yoko-s-maschwitz",
   "address" => " Mendoza 1731. Complejo Mercado de Maschwitz",
   "food-type" => "China",
   "price" => "$$",
   "discount" => "20",
   ),
   array(
   "name" => "Le Point",
   "sub" => "&nbsp;",
   "slug" => "le-point",
   "address" => " Soria 5172. Palermo",
   "food-type" => "De autor",
   "price" => "$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Yoko's",
   "sub" => "(Pilar)",
   "slug" => "yoko-s-pilar",
   "address" => " Panamericana km 49,5 Ed. Bureau Pilar. Pilar",
   "food-type" => "China",
   "price" => "$$",
   "discount" => "20",
   ),
   array(
   "name" => "Kanú Sushi",
   "sub" => "&nbsp;",
   "slug" => "kanu-sushi",
   "address" => " Borges 1813. Palermo",
   "food-type" => "Sushi",
   "price" => "$$$$",
   "discount" => "20",
   ),
   array(
   "name" => "OHANA Bar & Lounge",
   "sub" => "&nbsp;",
   "slug" => "ohana-bar-lounge",
   "address" => " Niceto Vega 5737. Palermo",
   "food-type" => "Picadas",
   "price" => "$$$",
   "discount" => "25",
   ),
   array(
   "name" => "Akira",
   "sub" => "(Núñez)",
   "slug" => "akira-nunez",
   "address" => " Besares 1700. Núñez",
   "food-type" => "Sushi",
   "price" => "$$$$",
   "discount" => "20",
   ),	  
/*   array(
   "name" => "Akira Sushi",
   "sub" => "(Olivos)",
   "slug" => "akira-sushi-olivos",
   "address" => " Av. Libertador 2845. Olivos",
   "food-type" => "Sushi",
   "price" => "$$$$",
   "discount" => "20",
   ),*/
   array(
   "name" => "Las Nazarenas",
   "sub" => "&nbsp;",
   "slug" => "las-nazarenas",
   "address" => " Reconquista 1132. Centro",
   "food-type" => "Parrilla",
   "price" => "$$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Trova",
   "sub" => "(Wine Bar)",
   "slug" => "trova-wine-bar",
   "address" => " Honduras 5909. Palermo",
   "food-type" => "De autor",
   "price" => "$$$",
   "discount" => "20", //Hasta 30
   ),
   array(
   "name" => "A la Casona del Nonno",
   "sub" => "&nbsp;",
   "slug" => "a-la-casona-del-nonno",
   "address" => " Lavalle 827. Centro",
   "food-type" => "Internacional",
   "price" => "$$",
   "discount" => "30",
   ),
   array(
   "name" => "Nosu Sushi",
   "sub" => "(Paseo Pilar)",
   "slug" => "nosu-sushi-paseo-pilar",
   "address" => " Panamericana km 44. Paseo Pilar",
   "food-type" => "Sushi",
   "price" => "$$$",
   "discount" => "20",
   ),
//   array(
//   "name" => "De Quién?",
//   "sub" => "&nbsp;",
//   "slug" => "de-quien",
//   "address" => " Honduras 4141. Palermo",
//   "food-type" => "De autor",
//   "price" => "$$$",
//   "discount" => "20",
//   ),
   array(
   "name" => "Set Point",
   "sub" => "&nbsp;",
   "slug" => "set-point",
   "address" => " Agustín García 5200. Tigre",
   "food-type" => "Pastas",
   "price" => "$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Bistró Recoleta",
   "sub" => "(Meliá Recoleta Plaza Hotel)",
   "slug" => "bistro-recoleta-melia-recoleta-plaza-hotel",
   "address" => " Posadas 1557. Recoleta",
   "food-type" => "Internacional",
   "price" => "$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Pasta Rossa",
   "sub" => "(Canning)",
   "slug" => "pasta-rossa-canning",
   "address" => " Mariano Castex 1277. Canning",
   "food-type" => "Española",
   "price" => "$$",
   "discount" => "20",
   ),
   array(
   "name" => "Mott",
   "sub" => "(Palermo)",
   "slug" => "mott-palermo",
   "address" => " El Salvador 4685. Palermo",
   "food-type" => "De autor",
   "price" => "$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Little Rose",
   "sub" => "&nbsp;",
   "slug" => "little-rose",
   "address" => "Armenia 1672, 1° Piso. Palermo",
   "food-type" => "Sushi",
   "price" => "$$$$",
   "discount" => "20",
   ),
//   array(
//   "name" => "Vinario",
//   "sub" => "&nbsp;",
//   "slug" => "vinario",
//   "address" => " Beruti 2751. Recoleta",
//   "food-type" => "De autor",
//   "price" => "$$$$",
//   "discount" => "25",
//   ),
   array(
   "name" => "Alvear San Isidro",
   "sub" => "&nbsp;",
   "slug" => "alvear-san-isidro",
   "address" => " Belgrano 107. San Isidro",
   "food-type" => "Parrilla",
   "price" => "$$",
   "discount" => "20",
   ),
   array(
   "name" => "Spoon",
   "sub" => "&nbsp;",
   "slug" => "spoon",
   "address" => " Dardo Rocha 2002. Martinez",
   "food-type" => "Internacional",
   "price" => "$$$",
   "discount" => "20", //Hasta 30
   ),
   array(
   "name" => "La Popular del Soho",
   "sub" => "&nbsp;",
   "slug" => "la-popular-del-soho",
   "address" => " Guatemala 4701. Palermo",
   "food-type" => "Parrilla",
   "price" => "$$$",
   "discount" => "20",
   ), 
   array(
   "name" => "Buono",
   "sub" => "&nbsp;",
   "slug" => "buono",
   "address" => " San Martin 1225. Retiro",
   "food-type" => "Italiana",
   "price" => "$$$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Mykonos",
   "sub" => "&nbsp;",
   "slug" => "mykonos",
   "address" => " Baez 340. Las Cañitas" ,
   "food-type" => "Griega",
   "price" => "$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Frais",
   "sub" => "&nbsp;",
   "slug" => "frais",
   "address" => "Azcuénaga 1781. Recoleta" ,
   "food-type" => "Finger Foods",
   "price" => "$$",
   "discount" => "20",
   ),
);
   ?>