<?php
  $restaurants_personnalite = array(
   array(
   "name" => "St. Regis",
   "sub" => "(Park Tower Hotel)",
   "slug" => "st-regis-park-tower-hotel",
   "address" => "Av. Leandro N. Alem 1193. Recoleta",
   "food-type" => "Autóctona",
   "price" => "$$$$",
   "discount" => "20",
   ),
//   array(
//   "name" => "La Rosa Náutica",
//   "sub" => "&nbsp;",
//   "slug" => "la-rosa-nautica",
//   "address" => "Av. Alicia Moreau de Justo 246/256. Puerto Madero",
//   "food-type" => "Peruana",
//   "price" => "$$$",
//   "discount" => "20",
//   ),
   array(
   "name" => "Marinas Bay",
   "sub" => "&nbsp;",
   "slug" => "marinas-bay",
   "address" => " Agustín García 5200. Tigre",
   "food-type" => "Peruana",
   "price" => "$$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Green Bamboo",
   "sub" => "&nbsp;",
   "slug" => "green-bamboo",
   "address" => "Costa Rica 5802. Palermo" ,
   "food-type" => "Sudeste asiático",
   "price" => "$$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Le Grill Buenos Aires",
   "sub" => "&nbsp;",
   "slug" => "le-grill-buenos-aires",
   "address" => " Av. Alicia Moreau de Justo 876. Puerto Madero" ,
   "food-type" => "Parrilla",
   "price" => "$$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Il Matterello",
   "sub" => "(Palermo)",
   "slug" => "il-matterello-palermo",
   "address" =>  "Thames 1490. Palermo" ,
   "food-type" => "Italiana",
   "price" => "$$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Ravello",
   "sub" => "&nbsp;",
   "slug" => "ravello",
   "address" =>  "Honduras 5906. Palermo" ,
   "food-type" => "Parrilla",
   "price" => "$$",
   "discount" => "25",
   ),
//   array(
//   "name" => "Il Duce",
//   "sub" => "&nbsp;",
//   "slug" => "il-duce",
//   "address" =>  "Arce 305. Las Cañitas" ,
//   "food-type" => "India",
//   "price" => "$$$$$",
//   "discount" => "20",
//   ),
// 15/04
   array(
   "name" => "Ceviche",
   "sub" => "(Plaza Armenia)",
   "slug" => "ceviche-plaza-armenia",
   "address" => " Armenia 180. Palermo",
   "food-type" => "Peruana",
   "price" => "$$$",
   "discount" => "20",
   ),  
   array(
   "name" => "Ceviche",
   "sub" => "(Remeros Plaza)",
   "slug" => "ceviche-remeros-plaza",
   "address" => " Av. Santa Maria de las Conchas 4711. Zona Norte",
   "food-type" => "Peruana",
   "price" => "$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Ceviche",
   "sub" => "(Pilar)",
   "slug" => "ceviche-pilar",
   "address" => "Panamericana Km 43,5 (La Aldea). Pilar",
   "food-type" => "Peruana",
   "price" => "$$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Patio Japonés",
   "sub" => "&nbsp;",
   "slug" => "patio-japones",
   "address" => "Juana Manso 1616. Puerto Madero",
   "food-type" => "Fusión",
   "price" => "$$$",
   "discount" => "25",
   ),
   array(
   "name" => "Lupita",
   "sub" => "(Puerto Madero)",
   "slug" => "lupita-puerto-madero",
   "address" => "Olga Cossettini 1091. Puerto Madero",
   "food-type" => "Mexicana",
   "price" => "$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Lupita",
   "sub" => "(Palermo)",
   "slug" => "lupita-palermo",
   "address" => "Fitz Roy 1834. Palermo",
   "food-type" => "Mexicana",
   "price" => "$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Lupita",
   "sub" => "(Las Cañitas)",
   "slug" => "lupita-las-canitas",
   "address" => "Báez 227. Las Cañitas",
   "food-type" => "Mexicana",
   "price" => "$$$",
   "discount" => "20",
   ),
   array(
   "name" => "Lupita",
   "sub" => "(Martínez)",
   "slug" => "lupita-martinez",
   "address" => "Av. del Libertador Gral. San Martín 14186. Zona Norte",
   "food-type" => "Mexicana",
   "price" => "$$$",
   "discount" => "20",
   ),
      
      
);
   ?>