<?php
  $restaurants = array(
    array(
		"name" => "St. Regis",
		"sub" => "(Park Tower Hotel)",
		"slug" => "st-regis-park-tower-hotel",
		"id" => "1510",
		"address" => "Av. Leandro N. Alem 1193 / Recoleta",
		"food-type" => "Autóctona",
		"price" => "$$$$",
		"discount" => "30",
	),
//    array(
//		"name" => "Cardinale",
//		"sub" => "(Hotel Sheraton Buenos Aires)",
//		"slug" => "cardinale-hotel-sheraton-buenos-aires",
//		"id" => "1511",
//		"address" => "San Martin 1225 / Recoleta",
//		"food-type" => "Italiana",
//		"price" => "$$$",
//		"discount" => "30",
//	),
	array(
		"name" => "Club 31 Bar & Resto",
		"slug" => "club-31-bar-resto-buenos-aires-grand-hotel",
		"id" => "2755",
		"address" => "Av. Gral. Las Heras 1745 / Recoleta",
		"food-type" => "Autóctona",
		"price" => "$$$$",
		"discount" => "30",
	),
//	array(
//		"name" => "Marieta",
//		"slug" => "marieta",
//		"id" => "6194",
//		"address" => "Cerrito 22 / Centro",
//		"food-type" => "Mediterránea",
//		"price" => "$$$$",
//		"discount" => "30",
//	),
	array(
		"name" => "Il Matterello",
		"sub" => "(Palermo)",
		"slug" => "il-matterello-palermo",
		"id" => "9382",
		"address" => "Gorriti 5110 / Palermo",
		"food-type" => "Italiana",
		"price" => "$$$",
		"discount" => "20",
	),	
	array(
		"name" => "Il Matterello",
		"sub" => "(La Boca)",
		"slug" => "il-matterello-la-boca",
		"id" => "1434",
		"address" => " Martin Rodriguez 517 / La Boca",
		"food-type" => "Italiana",
		"price" => "$$$$",
		"discount" => "20",
	),	
	array(
		"name" => "Harturo",
		"slug" => "harturo",
		"id" => "9446",
		"address" => "Vicente López 1661. Puerta 12 / Recoleta",
		"food-type" => "Porteña",
		"price" => "$$$$",
		"discount" => "20",
	),
//	array(
//		"name" => "Trova (Wine Bar)",
//		"slug" => "trova-wine-bar",
//		"id" => "5804",
//		"address" => "Honduras 5909 / Palermo",
//		"food-type" => "De autor",
//		"price" => "$$$",
//		"discount" => "20",
//	),
	array(
		"name" => "Le Grill Buenos Aires",
		"slug" => "le-grill-buenos-aires",
		"id" => "1721",
		"address" => "Av. Alicia Moreau de Justo 876 / Puerto Madero",
		"food-type" => "Parrilla",
		"price" => "$$$$",
		"discount" => "20",
	),
//    array(
//		"name" => "Topinambour",
//		"slug" => "topinambour",
//		"id" => "7465",
//		"address" => "Bonpland 2275 / Palermo",
//		"food-type" => "De autor",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
    array(
		"name" => "Maleva",
		"sub" => "(Palermo)",
		"slug" => "maleva-palermo",
		"id" => "2591",
		"address" => " Serrano 1598 / Palermo",
		"food-type" => "Internacional",
		"price" => "$$",
		"discount" => "20",
	),
	  array(
		"name" => "Meridiano 58",
		"slug" => "meridiano-58",
		"id" => "50",
		"address" => "Jorge L. Borges 1689 / Palermo",
		"food-type" => "Internacional",
		"price" => "$$",
		"discount" => "20",
	),
    array(
		"name" => "Casa Cruz",
		"slug" => "casa-cruz",
		"id" => "69",
		"address" => "Uriarte 1658 / Palermo",
		"food-type" => "Porteña",
		"price" => "$$$$",
		"discount" => "20",
	),
//	array(
//		"name" => "Aldo's",
//		"slug" => "aldo-s",
//		"id" => "518",
//		"address" => "Moreno 372 / San Telmo",
//		"food-type" => "Clásica",
//		"price" => "$$$",
//		"discount" => "20",
//	),
	array(
		"name" => "Bobo Restaurant",
		"sub" => "(Hotel Bo Bo)",
		"slug" => "bobo-restaurant-hotel-bo-bo",
		"id" => "1084",
		"address" => "Guatemala 4870 / Palermo",
		"food-type" => "De autor",
		"price" => "$$$",
		"discount" => "20",
	),
	array(
		"name" => "Sivela 465",
		"slug" => "sivela-465",
		"id" => "2150",
		"address" => "Av. Quintana 465 / Recoleta",
		"food-type" => "De autor",
		"price" => "$$$",
		"discount" => "20",
	),
	array(
		"name" => "Contraluz",
		"sub" => "(Alvear Art Hotel)",
		"slug" => "contraluz-alvear-art-hotel",
		"id" => "2873",
		"address" => "Suipacha 1036 / Recoleta ",
		"food-type" => "De autor",
		"price" => "$$$$",
		"discount" => "20",
	),
//	array(
//		"name" => "Jolie Bistro & Art Gallery",
//		"slug" => "jolie-bistro-art-gallery",
//		"id" => "312",
//		"address" => "Conde 2036 / Belgrano",
//		"food-type" => "De autor",
//		"price" => "$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Akira Nikkei",
//		"sub" => "(Palermo)",
//		"slug" => "La Cabrera (Barranco)-nikkei-palermo",
//		"id" => "3247",
//		"address" => "Cavia 3090 / Palermo",
//		"food-type" => "Sushi",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Akira Nikkei",
//		"sub" => "(Acassuso)",
//		"slug" => "La Cabrera (Barranco)-nikkei-acassuso",
//		"id" => "2047",
//		"address" => "Av. del Libertador 15431 / Zona Norte",
//		"food-type" => "Peruana",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Akira La Maison",
//		"sub" => "(Martínez)",
//		"slug" => "La Cabrera (Barranco)-la-maison-martinez",
//		"id" => "2045",
//		"address" => "Gral. Paunero 2031 / Zona Norte",
//		"food-type" => "Japonesa",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
	array(
		"name" => "Lo de Jesús",
		"slug" => "lo-de-jesus",
		"id" => "1334",
		"address" => "Gurruchaga 1406 / Palermo",
		"food-type" => "Parrilla",
		"price" => "$$$",
		"discount" => "20",
	),
//	array(
//		"name" => "Akira Sushi",
//		"sub" => "(Lomas de San Isidro)",
//		"slug" => "La Cabrera (Barranco)-sushi-lomas-de-san-isidro",
//		"id" => "2044",
//		"address" => "Diego Palma 1516 / Zona Norte",
//		"food-type" => "Japonesa",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Akira",
//		"sub" => "(Núñez)",
//		"slug" => "akira-nunez",
//		"id" => "6281",
//		"address" => "Besares 1700 / Núñez",
//		"food-type" => "Japonesa",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Akira",
//		"sub" => "(Olivos)",
//		"slug" => "La Cabrera (Barranco)-olivos",
//		"id" => "6758",
//		"address" => "Av. Libertador 2845 / Zona Norte",
//		"food-type" => "Japonesa",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Akira Sushi & Nikkei",
//		"sub" => "(Centro)",
//		"slug" => "La Cabrera (Barranco)-sushi-nikkei-centro",
//		"id" => "7430",
//		"address" => "Pje. Ricardo Rojas 451 / Retiro",
//		"food-type" => "Sushi",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Campobravo",
//		"sub" => "(Palermo)",
//		"slug" => "campobravo-palermo--2",
//		"id" => "1250",
//		"address" => "Honduras 5600 / Palermo",
//		"food-type" => "Carnes",
//		"price" => "$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Campobravo",
//		"sub" => "(Las Cañitas)",
//		"slug" => "campobravo-las-canitas",
//		"id" => "148",
//		"address" => "Báez 292 / Las Cañitas",
//		"food-type" => "Carnes",
//		"price" => "$$",
//		"discount" => "20",
//	),
	array(
		"name" => "Tg Restó",
		"slug" => "tg-resto",
		"id" => "6711",
		"address" => "Spiro 831, Adrogué / Zona Sur",
		"food-type" => "De autor",
		"price" => "$$$",
		"discount" => "20",
	),
//	array(
//			"name" => "BRAČ",
//			"slug" => "brac",
//			"id" => "7138",
//			"address" => "Humboldt 1864 / Palermo",
//			"food-type" => "De autor",
//			"price" => "$$$$",
//			"discount" => "20",
//		),
	array(
		"name" => "Primafila",
		"slug" => "primafila",
		"id" => "1107",
		"address" => "Av. Pueyrredón 2501 / Recoleta",
		"food-type" => "Italiana",
		"price" => "$$$",
		"discount" => "20",
	),
//	array(
//		"name" => "La Rosa Náutica",
//		"slug" => "la-rosa-nautica",
//		"id" => "1873",
//		"address" => "Av. Alicia Moreau de Justo 246 / Puerto Madero",
//		"food-type" => "Pescados y Mariscos",
//		"price" => "$$$",
//		"discount" => "20",
//	),
	array(
		"name" => "El Federal",
		"slug" => "el-federal",
		"id" => "576",
		"address" => "San Martín 1015 / Centro",
		"food-type" => "De autor",
		"price" => "$$$",
		"discount" => "20",
	),
//	array(
//		"name" => "La Causa Nikkei",
//		"slug" => "la-causa-nikkei",
//		"id" => "6459",
//		"address" => "Callao 1290 / Recoleta",
//		"food-type" => "Nikkei",
//		"price" => "$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "La Cabaña",
//		"slug" => "la-cabana",
//		"id" => "500",
//		"address" => "Av. Alicia Moreau de Justo 380 / Puerto Madero",
//		"food-type" => "Parrilla",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "DOC Vinos y Cocina",
//		"sub" => "(Córdoba)",
//		"slug" => "doc-vinos-y-cocina",
//		"id" => "7301",
//		"address" => "Av. Concepción Arenal 1018 / Nueva Córdoba",
//		"food-type" => "Mediterránea",
//		"price" => "$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Cuina",
//		"slug" => "cuina",
//		"id" => "6380",
//		"address" => "Moreno 298 / Ramos Mejía",
//		"food-type" => "De autor",
//		"price" => "$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Casa Coupage",
//		"slug" => "casa-coupage",
//		"id" => "1132",
//		"address" => "Soler 5518 / Palermo",
//		"food-type" => "De autor",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "SHOUT Brasas & Drinks",
//		"slug" => "shout-brasas-drinks",
//		"id" => "7039",
//		"address" => "Maipú 981 / Retiro",
//		"food-type" => "Gourmet",
//		"price" => "$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Ceviche",
//		"sub" => "(Pilar)",
//		"slug" => "ceviche-pilar",
//		"id" => "1290",
//		"address" => "Ruta Panamericana KM 43,5 (Cjo. la Aldea) / Pilar",
//		"food-type" => "Peruana",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Primi Piatti",
//		"slug" => "primi-piatti",
//		"id" => "3025",
//		"address" => "French 3001 / Recoleta",
//		"food-type" => "Mediterránea",
//		"price" => "$$$",
//		"discount" => "20",
//	),
	array(
		"name" => "Plaza Grill",
		"slug" => "plaza-grill",
		"id" => "2301",
		"address" => "Florida 1005 / Retiro",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "20",
	),
	array(
		"name" => "Cucina D'onore",
		"slug" => "cucina-d-onore",
		"id" => "161",
		"address" => "Av. Alicia Moreau de Justo 1768 / Puerto Madero",
		"food-type" => "Mediterránea",
		"price" => "$$$",
		"discount" => "20",
	),
//	array(
//		"name" => "Los Aliños",
//		"sub" => "(Córdoba)",
//		"slug" => "los-alinos-howard-johnson-hotel-suites-la-canada",
//		"id" => "6831",
//		"address" => "Figueroa Alcorta 20 / Córdoba Centro",
//		"food-type" => "De autor",
//		"price" => "$$",
//		"discount" => "20",
//	),
	array(
		"name" => "La Popular del Soho",
		"slug" => "la-popular-del-soho",
		"id" => "6723",
		"address" => "Guatemala 4701 / Palermo",
		"food-type" => "Parrilla",
		"price" => "$$$",
		"discount" => "20",
	),
//	array(
//		"name" => "La Ventola",
//		"slug" => "la-ventola",
//		"id" => "368",
//		"address" => "Elcano 1700 / Martínez",
//		"food-type" => "Pescados y Mariscos",
//		"price" => "$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Il Duce",
//		"slug" => "il-duce",
//		"id" => "8495",
//		"address" => "Arce 305  / Las Cañitas",
//		"food-type" => "Fusión",
//		"price" => "$$$$$",
//		"discount" => "20",
//	),
//	array(
//		"name" => "Don",
//		"slug" => "don",
//		"id" => "436",
//		"address" => "Arcos 1836 / Belgrano",
//		"food-type" => "De autor",
//		"price" => "$$$$",
//		"discount" => "20",
//	),
	array(
		"name" => "Buono",
		"slug" => "buono",
		"id" => "10017",
		"address" => "San Martín 1225 / Retiro",
		"food-type" => "Italiana",
		"price" => "$$$$$",
		"discount" => "20",
	),
	array(
		"name" => "Mizuki",
		"slug" => "mizuki",
		"id" => "9914",
		"address" => "Av. Juana Manso 1519 / Puerto Madero",
		"food-type" => "Japonesa",
		"price" => "$$$$$",
		"discount" => "20",
	),
	array(
		"name" => "Ceviche",
		"sub" => "(Plaza Armenia)",
		"slug" => "ceviche-plaza-armenia",
		"id" => "10128",
		"address" => "Armenia 1880 / Palermo",
		"food-type" => "Peruana",
		"price" => "$$$",
		"discount" => "20",
	),
	array(
		"name" => "Lupita",
		"sub" => "(Las Cañitas)",
		"slug" => "lupita-las-canitas",
		"id" => "234",
		"address" => "Báez 227 / Las Cañitas",
		"food-type" => "Mexicana",
		"price" => "$$$",
		"discount" => "20",
	),
    array(
		"name" => "Lupita",
		"sub" => "(Puerto Madero)",
		"slug" => "lupita-puerto-madero",
		"id" => "1560",
		"address" => "Olga Cossettini 1091 / Puerto Madero",
		"food-type" => "Mexicana",
		"price" => "$$$",
		"discount" => "20",
	),
    array(
		"name" => "Lupita",
		"sub" => "(Palermo)",
		"slug" => "lupita-palermo",
		"id" => "3086",
		"address" => "Fitz Roy 1834 / Palermo",
		"food-type" => "Mexicana",
		"price" => "$$$",
		"discount" => "20",
	),
//    array(
//		"name" => "Lupita",
//		"sub" => "(Martínez)",
//		"slug" => "lupita-martinez",
//		"id" => "8320",
//		"address" => "	Av del Libertador General San Martín 14186",
//		"food-type" => "Mexicana",
//		"price" => "$$$",
//		"discount" => "20",
//	),
//    array(
//		"name" => "Lupita",
//		"sub" => "(Quilmes)",
//		"slug" => "lupita-quilmes",
//		"id" => "10218",
//		"address" => "Brown 397",
//		"food-type" => "Mexicana",
//		"price" => "$$$",
//		"discount" => "20",
//	),
    array(
		"name" => "Pacifica Bar de Mar",
		"slug" => "pacifica-bar-de-mar",
		"id" => "9966",
		"address" => "Thames 1402 / Palermo",
		"food-type" => "Peruana",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Rodizio",
        "sub" => "(Puerto Madero)",
		"slug" => "rodizio-puerto-madero",
		"id" => "167",
		"address" => "Alicia Moreau de Justo 838 / Puerto Madero",
		"food-type" => "Autóctona",
		"price" => "$$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Rodizio",
        "sub" => "(Costanera Norte)",
		"slug" => "rodizio-costanera-norte",
		"id" => "1100",
		"address" => "Av. Rafael Obligado 6551 / Costanera Norte",
		"food-type" => "Internacional",
		"price" => "$$$$$",
		"discount" => "20",
	),
//    array(
//		"name" => "Mir O'Hashi",
//        "sub" => "(Martínez)",
//		"slug" => "mir-o-hashi-martinez",
//		"id" => "1338",
//		"address" => "Av. Del Libertador 13946 / Martínez",
//		"food-type" => "Sushi",
//		"price" => "$$",
//		"discount" => "30",
//	),
//    array(
//		"name" => "Mir O'Hashi",
//        "sub" => "(San Isidro)",
//		"slug" => "mir-o-hashi-san-isidro",
//		"id" => "1337",
//		"address" => "Av. Sucre 2146 / Lomas de San Isidro",
//		"food-type" => "Sushi",
//		"price" => "$$",
//		"discount" => "30",
//	),
//    array(
//		"name" => "Carmin Parrilla Urbana",
//        "sub" => "(Palermo)",
//		"slug" => "carmin-parrilla-urbana-palermo",
//		"id" => "8219",
//		"address" => "Honduras 5702 / Palermo",
//		"food-type" => "Parrilla",
//		"price" => "$$",
//		"discount" => "30",
//	),
  );
?>