<?php
  $restaurants_discount = array(
//    array(
//		"name" => "Mexicano Bras Mex Grill",
//		"sub" => "(Chile)",
//		"slug" => "mexicano-bras-mex-grill-chile",
//        "id" => "9199", 
//		"address" => "Rua Chile, 2135",
//        "zone" => "Rebouças",
//		"food-type" => " Mexicana",
//		"price" => "$$",
//		"discount" => "20",
//        "filters" => "reboucas mexicana 20",
//	),
//    array(
//		"name" => "Mexicano Bras Mex Grill",
//		"sub" => "(Alto da XV)",
//		"slug" => "mexicano-bras-mex-grill-alto-da-xv",
//        "id" => "9204", 
//		"address" => "Av. Marechal Humberto de Alencar Castelo Branco 295",
//        "zone" => "Alto da Rua XV",
//		"food-type" => " Mexicana",
//		"price" => "$$",
//		"discount" => "20",
//        "filters" => "alto-da-rua-xv mexicana 20",
//	),
//    array(
//		"name" => "Thai",
//		"sub" => "Restaurante Thailandês",
//		"slug" => "thai-restaurante-thailandes",
//        "id" => "1005", 
//		"address" => "Júlia Da Costa, 870",
//        "zone" => "Bigorrilho",
//		"food-type" => "Tailandesa",
//		"price" => "$$$$",
//		"discount" => "30",
//        "filters" => "bigorrilho tailandesa 30",
//	),
//    array(
//		"name" => "Tierra del Fuego",
//		"sub" => "(Batel)",
//		"slug" => "tierra-del-fuego-batel",
//        "id" => "8751", 
//		"address" => " Av. 7 de Setembro, 6260",
//        "zone" => "Batel",
//		"food-type" => "Argentina",
//		"price" => "$$",
//		"discount" => "30",
//        "filters" => "batel argentina 30",
//	),
    array(
		"name" => "Tierra del Fuego",
		"sub" => "(Juvevê)",
		"slug" => "tierra-del-fuego-juveve",
        "id" => "8754", 
		"address" => "Rua Barão de Guaraúna, 550",
        "zone" => "Juvevê",
		"food-type" => "Argentina",
		"price" => "$$",
		"discount" => "30",
        "filters" => "medellin",
	),
//    array(
//		"name" => "Montecristo",
//		"sub" => "&nbsp;",
//		"slug" => "montecristo",
//        "id" => "9209", 
//		"address" => "Rua Silveira Peixoto, 765",
//        "zone" => "Batel",
//		"food-type" => "Argentina",
//		"price" => "$$$",
//		"discount" => "20",
//        "filters" => "batel argentina 20",
//	),
//    array(
//		"name" => "Karbonell Gourmet",
//		"sub" => "&nbsp;",
//		"slug" => "karbonell-gourmet",
//        "id" => "9157", 
//        "zone" => "Alto da Rua XV",
//		"food-type" => "Contemporânea",
//		"price" => "$$",
//		"discount" => "10",
//        "filters" => "alto-da-rua-xv contemporanea 10",
//	),
//    array(
//		"name" => "Casa Do Zé Rodízio de Espetinhos",
//		"sub" => "&nbsp;",
//		"slug" => "casa-do-ze-rodizio-de-espetinhos",
//        "id" => "8499", 
//        "zone" => "Batel",
//		"food-type" => "Brasileira",
//		"price" => "$$$",
//		"discount" => "30",
//        "filters" => "batel brasileira 30",
//	),
	  
	  
	  
	  
	  

	  
  );
?>