<?php
  $restaurants = array(
    array(
		"name" => "La Fondue",
		"sub" => "(Swissotel)",
		"slug" => "la-fondue-swissotel",
		"id" => "6663",
		"address" => "Av. Santo Toribio 173-Vía Central 150",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "30",
	),
	array(
		"name" => "La Dama Juana",
		"slug" => "la-dama-juana",
		"id" => "4687",
		"address" => "Av. República de Panamá 230",
		"food-type" => "Peruana",
		"price" => "$$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Wallqa Restaurante",
		"slug" => "wallqa-restaurante",
		"id" => "6171",
		"address" => "Vasco Núñez de Balboa 530",
		"food-type" => "De Autor",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Cabos Restaurante Del Puerto",
		"slug" => "cabos-restaurante-del-puerto",
		"id" => "4421",
		"address" => "AV. Jorge Chavez 120, Callao",
		"food-type" => "Internacional",
		"price" => "$$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Nikko",
        "sub" => "(La Molina)",
		"slug" => "nikko",
		"id" => "7736",
		"address" => "Av. La Fontana 1137",
		"food-type" => "Nikkei",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Segundo Muelle",
		"sub" => "(Costa Verde)",
		"slug" => "segundo-muelle-costa-verde",
		"id" => "5179",
		"address" => "Av. Costa Verde s/n, Playa de las Cascadas",
		"food-type" => "Fusión",
		"price" => "$$$$",
		"discount" => "20",
	),
	array(
		"name" => "Aguaymanto",
        "sub" => "(Foresta Hotel Lima)",
		"slug" => "aguaymanto-foresta-hotel-lima",
		"id" => "4267",
		"address" => "Calle Los Libertadores 490",
		"food-type" => "Fusión",
		"price" => "$$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Restaurante y Bar 365",
		"slug" => "restaurante-y-bar-365",
		"id" => "10141",
		"address" => "Av. Victor Andrés Belaúnde 198",
		"food-type" => "Internacional",
		"price" => "$$$",
		"discount" => "30",
	),
    array(
		"name" => "Mirasol",
		"slug" => "mirasol",
		"id" => "4473",
		"address" => "Jirón Choquehuanca 209",
		"food-type" => "Peruana",
		"price" => "$$$$",
		"discount" => "25",
	),
    array(
		"name" => "Caplina",
        "sub" => "(Miraflores)",
		"slug" => "caplina-miraflores",
		"id" => "10152",
		"address" => "Santa Cruz 900",
		"food-type" => "Peruana",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Quimera Restaurante",
        "sub" => "(BTH Hotel)",
		"slug" => "quimera-restaurante-bth-hotel",
		"id" => "6997",
		"address" => "Av. Guardia Civil 727",
		"food-type" => "Fusión",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Pedrasa a la Brasa",
		"slug" => "los-pedrasa-a-la-brasa",
		"id" => "9965",
		"address" => "Av. Jorge Chávez 230",
		"food-type" => "Peruana",
		"price" => "$$",
		"discount" => "20",
	),
    array(
		"name" => "Baco & Vaca",
		"slug" => "baco-vaca",
		"id" => "7028",
		"address" => "Av. Dos de Mayo 798",
		"food-type" => "Parrilla",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "El Otro Parrillon",
		"slug" => "el-otro-parrillon",
		"id" => "5870",
		"address" => "Calle Los Cedros Mz. J Lote 3 C",
		"food-type" => "Carnes",
		"price" => "$$$",
		"discount" => "20",
	),
    array(
		"name" => "Nikko",
        "sub" => "(Miraflores)",
		"slug" => "nikko-miraflores",
		"id" => "10336",
		"address" => "Av. Mariscal La Mar 1285",
		"food-type" => "Nikkei",
		"price" => "$$$$",
		"discount" => "20",
	),
  );
?>