<?php
  $restaurants = array(
    // BOGOTA
    array(
		"name" => "Restaurante Daniel",
        "sub" => "",
		"slug" => "restaurante-daniel",
        "id" => "3358", 
		"address" => "Calle 73 # 9-70",
        "zone" => "Zona G",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "Donostia",
        "sub" => "",
		"slug" => "donostia",
        "id" => "2197", 
		"address" => "Calle 29 bis N° 5-84",
        "zone" => "La Macarena",
		"food-type" => "Colombiana",
		"price" => "$$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "La Ventana",
        "sub" => "",
		"slug" => "la-ventana",
        "id" => "7967", 
		"address" => "Carrera 7 No. 72-41",
        "zone" => "Chapinero",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "Tábula",
        "sub" => "",
		"slug" => "tabula",
        "id" => "2269", 
		"address" => "Calle. 29 Bis N° 5 - 90",
        "zone" => "La Macarena",
		"food-type" => "Colombiana",
		"price" => "$$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "Tramonti",
        "sub" => "",
		"slug" => "tramonti",
        "id" => "2273", 
		"address" => "Carrera 1ra N° 93-50",
        "zone" => "Chicó",
		"food-type" => "Italiana",
		"price" => "$$$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "Mister Ribs",
        "sub" => "(Usaquén)",
		"slug" => "mister-ribs-usaquen",
        "id" => "3684", 
		"address" => "Calle 119#6-06",
        "zone" => "Usaquén",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "20","filters" => "bogota",
	),
    array(
		"name" => "Mister Ribs",
        "sub" => "(Zona G)",
		"slug" => "mister-ribs-zona-g",
        "id" => "2243", 
		"address" => "Cr 6 #69a - 20",
        "zone" => "Zona G",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "Cook's",
        "sub" => "(Hotel Four Points by Sheraton)",
		"slug" => "cook-s",
        "id" => "8844", 
		"address" => "Carrera 18 93A-83",
        "zone" => "Parque de la 93",
		"food-type" => "Internacional",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "La Santa Guadalupe",
        "sub" => "",
		"slug" => "la-santa-guadalupe",
        "id" => "7531", 
		"address" => "Calle 109 No. 15 - 44",
        "zone" => "Usaquén",
		"food-type" => "Mexicana",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "Las 4 Estaciones",
        "sub" => "",
		"slug" => "las-4-estaciones",
        "id" => "3691", 
		"address" => "Carrera 8A #98-38",
        "zone" => "Chicó",
		"food-type" => "Española",
		"price" => "$$$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "Casa 9-69",
        "sub" => "",
		"slug" => "casa-9-69",
        "id" => "6990", 
		"address" => "Carrera 9 No. 69-07",
        "zone" => "Quinta Camacho",
		"food-type" => "Autóctona",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "Jaime Gourmet",
        "sub" => "Cocina Peruana",
		"slug" => "jaime-gourmet",
        "id" => "3596", 
		"address" => "Av. 127 #60-85",
        "zone" => "Suba",
		"food-type" => "Colombiana",
		"price" => "$$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "El Boliche La Macarena",
        "sub" => "(Candelaria)",
		"slug" => "el-boliche",
        "id" => "9647", 
		"address" => "Calle 12B No. 2 - 97",
        "zone" => "La Candelaria",
		"food-type" => "Pasta",
		"price" => "$$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "Toscana",
        "sub" => "",
		"slug" => "toscana",
        "id" => "8907", 
		"address" => "Km 23 Via - Guasca",
        "zone" => "La Calera",
		"food-type" => "Italiana",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
//    array(
//		"name" => "69 Gauchos",
//        "sub" => "",
//		"slug" => "69-gauchos",
//        "id" => "6912", 
//		"address" => "Calle 69a N 10 - 16",
//        "zone" => "Quinta Camacho",
//		"food-type" => "Parrilla",
//		"price" => "$$$$",
//		"discount" => "20",
//        "filters" => "bogota",
//	),
    array(
		"name" => "Mi Calle",
        "sub" => "",
		"slug" => "mi-calle",
        "id" => "5885", 
		"address" => "Calle 120A No 6 - 05",
        "zone" => "Usaquén",
		"food-type" => "Mexicana",
		"price" => "$$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    array(
		"name" => "Innovo Restaurante",
        "sub" => "",
		"slug" => "innovo-restaurante",
        "id" => "3448", 
		"address" => "Calle 69A # 5-59",
        "zone" => "Zona G",
		"food-type" => "Pescados y Mariscos",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "bogota",
	),
    // MEDELLIN
    array(
		"name" => "Bruno Forno e Vino",
        "sub" => "",
		"slug" => "bruno-forno-e-vino",
        "id" => "6251", 
		"address" => "Carrera 35 N°10B - 33",
        "zone" => "El Poblado",
		"food-type" => "Pizza",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "medellin",
	),
    array(
		"name" => "La Cava",
        "sub" => "(Hotel InterContinental)",
		"slug" => "la-cava",
        "id" => "8505", 
		"address" => "Calle 16 No. 28-51",
        "zone" => "Las Palmas",
		"food-type" => "Internacional",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "medellin",
	),
    array(
		"name" => "Angus Brangus",
        "sub" => "",
		"slug" => "angus-brangus",
        "id" => "5649", 
		"address" => "Carrera 42 #34-15",
        "zone" => "El Poblado",
		"food-type" => "Internacional",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "medellin",
	),
    array(
		"name" => "Herbario",
        "sub" => "",
		"slug" => "herbario",
        "id" => "5652", 
		"address" => "Carrera 43D 10-30",
        "zone" => "El Poblado",
		"food-type" => "Colombiana",
		"price" => "$$$$",
		"discount" => "20",
        "filters" => "medellin",
	),
    array(
		"name" => "Triada",
        "sub" => "",
		"slug" => "triada",
        "id" => "5084", 
		"address" => "Carrera 38 N°8-8",
        "zone" => "Parque Lleras",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "20",
        "filters" => "medellin",
	),
    array(
		"name" => "El Village",
        "sub" => "",
		"slug" => "el-village",
        "id" => "9776", 
		"address" => "Cra. 37A N°8A-33",
        "zone" => "Parque Lleras",
		"food-type" => "Fusión",
		"price" => "$$",
		"discount" => "20",
        "filters" => "medellin",
	),
    array(
		"name" => "Horny American Tavern",
        "sub" => "",
		"slug" => "horny-american-tavern",
        "id" => "10028", 
		"address" => "Carrera 35 # 10b 29",
        "zone" => "El Poblado",
		"food-type" => "Americana",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "medellin",
	),
    array(
		"name" => "Lupita Peruana-Mexicana",
        "sub" => "",
		"slug" => "lupita-peruana-mexicana",
        "id" => "5247", 
		"address" => "Carrera 43 N°52-40",
        "zone" => "Centro",
		"food-type" => "Mexicana",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "medellin",
	),
    array(
		"name" => "Fogón de Piedra",
        "sub" => "(Hotel InterContinental)",
		"slug" => "fogon-de-piedra",
        "id" => "8503", 
		"address" => "Calle 16 #28-51",
        "zone" => "Las Palmas",
		"food-type" => "Internacional",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "medellin",
	),
    array(
		"name" => "Paralelo17",
        "sub" => "",
		"slug" => "paralelo-17",
        "id" => "9450", 
		"address" => "Calle 8 No.43B-136",
        "zone" => "El Poblado",
		"food-type" => "Thai",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "medellin",
	),
    array(
		"name" => "Kuélap",
        "sub" => "",
		"slug" => "kuelap",
        "id" => "10197", 
		"address" => "Cl 3 Sur 43A 40",
        "zone" => "El Poblado",
		"food-type" => "Peruana",
		"price" => "$$$",
		"discount" => "20",
        "filters" => "medellin",
	),
  )
  ?>