<?php
  $restaurants = array(
    array(
		"name" => "Navia",
		"slug" => "navia",
        "id" => "8141", 
		"address" => "González Camarena 1205",
        "zone" => "Santa Fé",
		"food-type" => "Española",
		"price" => "$$$$",
		"discount" => "30",
	),
    array(
		"name" => "El Escorial",
		"slug" => "el-escorial",
        "id" => "7628", 
		"address" => "Avenida de la Paz 57",
        "zone" => "San Ángel",
		"food-type" => "Española",
		"price" => "$$$",
		"discount" => "30",
	),
    array(
		"name" => "George Mexico",
		"slug" => "george-mexico",
        "id" => "8280", 
		"address" => "Presidente Masaryk 192",
        "zone" => "Polanco",
		"food-type" => "Mediterránea",
		"price" => "$$$",
		"discount" => "30",
	),
    array(
		"name" => "Porter Steakhouse",
		"slug" => "porter-steakhouse",
        "id" => "9324", 
		"address" => "Julio Verne 102",
        "zone" => "Polanco",
		"food-type" => "Pescados y Mariscos",
		"price" => "$$$",
		"discount" => "30",
	),
    array(
		"name" => "Restaurante Tamayo",
		"slug" => "restaurante-tamayo",
        "id" => "7618", 
		"address" => "Paseo de la Reforma 51",
        "zone" => "Polanco",
		"food-type" => "Mexicana",
		"price" => "$$$",
		"discount" => "30",
	),
    array(
		"name" => "El Carmen Delicatessen",
		"slug" => "el-carmen-delicatessen",
        "id" => "8364", 
		"address" => "Plaza San Jacinto no 1",
        "zone" => "San Ángel",
		"food-type" => "Italiana",
		"price" => "$$$",
		"discount" => "30",
	),
    array(
		"name" => "Doba Gourmet",
		"slug" => "doba-gourmet",
        "id" => "8364", 
		"address" => "Av Las Fuentes 557",
        "zone" => "El Pedregal",
		"food-type" => "De autor",
		"price" => "$$",
		"discount" => "30",
	),
    array(
		"name" => "Campotoro",
		"slug" => "campotoro",
        "id" => "7916", 
		"address" => "Anatole France 70",
        "zone" => "Polanco",
		"food-type" => "Española",
		"price" => "$$$$",
		"discount" => "30",
	),
    array(
		"name" => "D'Kírico",
		"slug" => "dkirico",
        "id" => "9983", 
		"address" => "Calle de la Amargura 17",
        "zone" => "San Ángel",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "30",
	),
    array(
		"name" => "La Antigua",
		"slug" => "la-antigua",
        "id" => "9184", 
		"address" => "Gustavo Baz 2220",
        "zone" => "Tlalnepantla",
		"food-type" => "Mexicana",
		"price" => "$$",
		"discount" => "30",
	),
    array(
		"name" => "La Tecla",
		"slug" => "la-tecla",
        "id" => "9465", 
		"address" => "Durango 186",
        "zone" => "Roma",
		"food-type" => "Mexicana",
		"price" => "$$$",
		"discount" => "30",
	),
    array(
		"name" => "Casa Fran",
		"slug" => "casa-fran",
        "id" => "7800", 
		"address" => "Emilio Castelar 163",
        "zone" => "Polanco",
		"food-type" => "Española",
		"price" => "$$$$",
		"discount" => "30",
	),
    array(
		"name" => "Rubaiyat",
		"slug" => "rubaiyat",
        "id" => "9945", 
		"address" => "Presidente Masaryk 20",
        "zone" => "Polanco",
		"food-type" => "Cortes de carne",
		"price" => "$$$$",
		"discount" => "30",
	),
    array(
		"name" => "Palermo Cantina",
		"slug" => "palermo-cantina",
        "id" => "9434", 
		"address" => "Calz de los Leones 135",
        "zone" => "San Ángel",
		"food-type" => "Italiana",
		"price" => "$$$",
		"discount" => "30",
	),
  )
  ?>