<?php
  $restaurants = array(
    array(
		"name" => "Senz",
		"sub" => "(Mall Plaza Egaña)",
		"slug" => "senz-mall-plaza-egana",
		"id" => "7760",
		"address" => " 	Av. Larraín 5862, Local 4016 - La Reina",
		"food-type" => "Peruana",
		"price" => "$$$",
		"discount" => "20",
	),
	array(
		"name" => "The White Rabbit",
		"slug" => "the-white-rabbit",
		"id" => "2991",
		"address" => "Antonia López de Bello 0118 - Bellavista",
		"food-type" => "Internacional",
		"price" => "$$",
		"discount" => "20",
	),
	array(
		"name" => "Barandales",
		"slug" => "barandales",
		"id" => "9968",
		"address" => "Dardignac 64 - Recoleta",
		"food-type" => "Tapas",
		"price" => "$$$",
		"discount" => "20",
	),
	array(
		"name" => "Zabo",
		"slug" => "zabo",
		"id" => "7423",
		"address" => "Merced 346, Local H - Santiago Centro",
		"food-type" => "Internacional",
		"price" => "$$$",
		"discount" => "30",
	),	
	array(
		"name" => "Tondero",
		"slug" => "tondero",
		"id" => "10111",
		"address" => "Pedro de Valdivia 2765 - Ñuñoa",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "20",
	),	
	array(
		"name" => "Bar Italia",
		"slug" => "bar-italia",
		"id" => "3788",
		"address" => "Av. Italia 1423 - Providencia",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "20",
	),
	array(
		"name" => "MOTEMEI",
        "sub" => "(Cocina Taller)",
		"slug" => "motemei-cocina-taller",
		"id" => "3455",
		"address" => "Las Hualtatas - Vitacura",
		"food-type" => "Chilena",
		"price" => "$$$$$",
		"discount" => "20",
	),
	array(
		"name" => "QAMAQI",
		"slug" => "qamaqi",
		"id" => "10224",
		"address" => "Camino Al Volcan 16779 - San José de Maipo",
		"food-type" => "Internacional",
		"price" => "$$",
		"discount" => "20",
	),
    array(
		"name" => "Terranée",
		"sub" => "(Hotel Intercontinental)",
		"slug" => "terranee-hotel-intercontinental",
		"id" => "9801",
		"address" => "Avenida Vitacura 2885 - Las Condes",
		"food-type" => "De Autor",
		"price" => "$$$",
		"discount" => "20",
	),
	  array(
		"name" => "Bautista Gourmet",
		"slug" => "bautista-gourmet",
		"id" => "8978",
		"address" => "Nueva Costanera 3950 - Vitacura",
		"food-type" => "De Autor",
		"price" => "$$$$",
		"discount" => "20",
	),
	array(
		"name" => "Casaluz",
		"slug" => "casaluz",
		"id" => "1632",
		"address" => "Av. Italia 805 - Providencia",
		"food-type" => "Mediterránea",
		"price" => "$$$",
		"discount" => "20",
	),
	array(
		"name" => "Zully",
		"slug" => "zully",
		"id" => "7383",
		"address" => "Concha y Toro 34 - Santiago Centro",
		"food-type" => "Internacional",
		"price" => "$$$",
		"discount" => "20",
	),
	array(
		"name" => "Casa Esmeralda",
		"slug" => "casa-esmeralda",
		"id" => "9143",
		"address" => "Esmeralda 716 - Santiago Centro",
		"food-type" => "Chilena",
		"price" => "$$$",
		"discount" => "20",
	),
	array(
		"name" => "Territorio",
        "sub" => "(Hotel Noi Vitacura)",
		"slug" => "territorio-hotel-noi-vitacura",
		"id" => "8207",
		"address" => "Av. Nueva Costanera 3736 - Vitacura",
		"food-type" => "Internacional",
		"price" => "$$$$",
		"discount" => "20",
	),
	array(
		"name" => "La Bifería",
		"slug" => "la-biferia",
		"id" => "1835",
		"address" => "Pedro de Valdivia 065 - Providencia",
		"food-type" => "Carnes",
		"price" => "$$$",
		"discount" => "20",
	),
	array(
		"name" => "Anakena",
        "sub" => "(Grand Hyatt Santiago)",
		"slug" => "anakena-grand-hyatt-santiago",
		"id" => "4680",
		"address" => "Av. Kennedy 4601 - Las Condes",
		"food-type" => "Thailandesa",
		"price" => "$$$",
		"discount" => "20",
	),      
	array(
		"name" => "Cuper & Co",
		"slug" => "cuper-co",
		"id" => "6805",
		"address" => "Vitacura 6780 - Vitacura",
		"food-type" => "De Autor",
		"price" => "$$",
		"discount" => "20",
	), 
    array(
		"name" => "Pacto, Arte y Sensualidad",
		"slug" => "pacto-arte-y-sensualidad",
		"id" => "4708",
		"address" => "Manuel Montt 284 - Providencia",
		"food-type" => "De Autor",
		"price" => "$$",
		"discount" => "20",
	),
    array(
		"name" => "Culto, Sociedad de la Buena Música",
		"slug" => "culto-sociedad-de-la-buena-musica",
		"id" => "4710",
		"address" => "Estados Unidos 246 - Santiago Centro",
		"food-type" => "Tapas",
		"price" => "$$",
		"discount" => "20",
	),
    array(
		"name" => "Estró",
        "sub" => "(The Ritz-Carlton, Santiago)",
		"slug" => "estro-the-ritz-carlton-santiago",
		"id" => "1465",
		"address" => "El Alcalde 15 - Las Condes",
		"food-type" => "De Autor",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Catae",
        "sub" => "(Renaissance Santiago Hotel)",
		"slug" => "catae-renaissance-santiago-hotel",
		"id" => "10042",
		"address" => "Av Presidente Kennedy 4700 - Vitacura",
		"food-type" => "De Autor",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "La Pescadería de Walker",
        "sub" => "(Borderío)",
		"slug" => "la-pescaderia-de-walker-borderio",
		"id" => "1456",
		"address" => "Escrivá de Balaguer 6400 Local 4-A - Vitacura",
		"food-type" => "Pescados y Mariscos",
		"price" => "$$$",
		"discount" => "20",
	),
    array(
		"name" => "Matsuri",
        "sub" => "(Grand Hyatt Santiago)",
		"slug" => "matsuri-grand-hyatt-santiago",
		"id" => "4682",
		"address" => "Av. Kennedy 4601 - Las Condes",
		"food-type" => "Japonesa",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Senso",
        "sub" => "(Grand Hyatt Santiago)",
		"slug" => "senso-grand-hyatt-santiago",
		"id" => "4689",
		"address" => "Av. Kennedy 4601 - Las Condes",
		"food-type" => "Mediterránea",
		"price" => "$$$",
		"discount" => "20",
	),
  );
?>