<?php
  $restaurants = array(
    array(
		"name" => "Frais",
        "sub" => "",
		"slug" => "frais",
        "id" => "5421", 
		"address" => "Azcuénaga 1781",
        "zone" => "Recoleta",
		"food-type" => "Finger Foods",
		"price" => "$$",
		"discount" => "20",
	),
    array(
		"name" => "Caracas Bar",
        "sub" => "",
		"slug" => "caracas-bar",
        "id" => "1849", 
		"address" => "Guatemala 4802",
        "zone" => "Palermo",
		"food-type" => "Latinoamericana",
		"price" => "$$$",
		"discount" => "20",
	),
    array(
		"name" => "La Dolfina Polo Bar",
        "sub" => "",
		"slug" => "la-dolfina-polo-bar",
        "id" => "10124", 
		"address" => "Av. Figueroa Alcorta 3301",
        "zone" => "Palermo",
		"food-type" => "Tapas",
		"price" => "$$",
		"discount" => "20",
	),
    array(
		"name" => "Artesano",
        "sub" => "",
		"slug" => "artesano",
        "id" => "10124", 
		"address" => "Suipacha 1036",
        "zone" => "Retiro",
		"food-type" => "Tapas",
		"price" => "$$$",
		"discount" => "20",
	),
    array(
		"name" => "Izakaya by Sushi Pop",
        "sub" => "(Palermo)",
		"slug" => "izakaya-by-sushi-pop-palermo",
        "id" => "10124", 
		"address" => "Soler 5596",
        "zone" => "Palermo",
		"food-type" => "Japonesa",
		"price" => "$$$",
		"discount" => "20",
	),
    array(
		"name" => "Celtic Pub",
        "sub" => "",
		"slug" => "celtic-pub",
        "id" => "8267", 
		"address" => "Carlos Pellegrini 551",
        "zone" => "Centro",
		"food-type" => "Tapas",
		"price" => "$$$",
		"discount" => "20",
	),
    array(
		"name" => "Raffaella",
        "sub" => "",
		"slug" => "raffaella",
        "id" => "2002", 
		"address" => "Talcahuano 52",
        "zone" => "Centro",
		"food-type" => "Internacional",
		"price" => "$$$",
		"discount" => "20",
	),
    array(
		"name" => "Negroni",
        "sub" => "",
		"slug" => "negroni",
        "id" => "1972", 
		"address" => "El Salvador 5602",
        "zone" => "Palermo",
		"food-type" => "Internacional",
		"price" => "$$$",
		"discount" => "20",
	),
    array(
		"name" => "Ralph's Bistro & Bar",
        "sub" => "",
		"slug" => "ralph-s-bistro-bar",
        "id" => "5091", 
		"address" => "Gurruchaga 1830",
        "zone" => "Palermo",
		"food-type" => "De autor",
		"price" => "$$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Plaza Bar",
        "sub" => "",
		"slug" => "plaza-bar",
        "id" => "2868", 
		"address" => "Florida 1005",
        "zone" => "Retiro",
		"food-type" => "Variada",
		"price" => "$$",
		"discount" => "20",
	),
    array(
		"name" => "La Princesa Resto - Bar",
        "sub" => "",
		"slug" => "la-princesa-resto-bar",
        "id" => "3748", 
		"address" => "Florida 1005",
        "zone" => "Retiro",
		"food-type" => "Variada",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Jackie O Restaurant",
        "sub" => "",
		"slug" => "jackie-o-restaurant",
        "id" => "1837", 
		"address" => "Báez 334",
        "zone" => "Las Cañitas",
		"food-type" => "Variada",
		"price" => "$$$$",
		"discount" => "20",
	),
    array(
		"name" => "Tres80 Resto-Bar",
        "sub" => "",
		"slug" => "tres80-resto-bar",
        "id" => "9926", 
		"address" => "Av. La Plata 380",
        "zone" => "Caballito",
		"food-type" => "Internacional",
		"price" => "$$",
		"discount" => "20",
	),
  )
  ?>